In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [3]:
df = pd.read_csv("forex_predictions_data.csv")

In [4]:
df.shape

(229, 10)

In [5]:
df.head(15)

,Date,Open,High,Low,Close,Volume,Predicted_Close,Currency_Pair,Signal,Confidence
0,2024-01-01,1.18727,1.92461,0.85312,1.18154,2201,1.22984,EUR/USD,Hold,0.90
1,2024-01-02,1.47536,1.82881,0.54067,1.32296,error,1.03797,EUR/USD,Sell,NaN
2,2024-01-03,1.36600,1.78415,0.54242,1.28539,4420,1.03888,EUR/USD,Sell,NaN
3,2024-01-04,1.29933,1.54684,0.99332,1.17805,4079,1.00117,EUR/USD,Sell,0.64
4,2024-01-05,1.07801,1.68386,0.68714,NaN,1832,1.48385,EUR/USD,Sell,0.68
5,2024-01-06,1.07800,1.63260,0.68532,1.30289,error,1.00263,EUR/USD,Buy,0.69
6,2024-01-07,1.02904,1.62199,0.90640,NaN,3806,1.05155,EUR/USD,Buy,0.73
7,2024-01-08,1.43309,1.98651,0.97362,1.05089,NaN,1.15730,EUR/USD,Hold,0.92
8,2024-01-09,1.30056,1.69655,0.99300,1.07643,3007,1.40372,EUR/USD,Buy,0.62
9,2024-01-10,1.35404,1.94602,0.87669,1.12298,3006,1.48105,EUR/USD,Buy,0.89
10,2024-01-11,1.01029,1.81557,0.68813,1.08034,3490,1.39501,EUR/USD,Hold,0.70
11,2024-01-12,1.48495,1.89741,0.54175,1.09328,2790,1.34528,EUR/USD,Hold,0.80
12,2024-01-13,1.41622,1.75132,0.88857,1.14255,1327,1.26065,EUR/USD,Hold,0.82
13,2024-01-14,1.10617,1.78845,0.77920,1.08669,4125,1.04335,EUR/USD,Buy,0.69
14,2024-01-15,1.09091,1.74626,0.71211,1.44838,3808,1.47909,EUR/USD,Buy,0.76

In [6]:
df.describe()

,Open,High,Low,Close,Predicted_Close,Confidence
count,224.000000,220.000000,225.000000,212.000000,222.000000,218.000000
mean,1.239946,1.753113,0.750030,1.245072,1.250415,0.756468
std,0.148956,0.147816,0.150434,0.140594,0.156102,0.135125
min,1.002530,1.505420,0.505680,1.002320,1.000120,0.500000
25%,1.111860,1.638832,0.614320,1.122535,1.115280,0.652500
50%,1.248105,1.763400,0.746310,1.235910,1.259605,0.760000
75%,1.365100,1.877682,0.877570,1.368805,1.392158,0.870000
max,1.493440,1.995250,0.999860,1.498440,1.499680,1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             226 non-null    object
 1   Open             224 non-null    float64
 2   High             220 non-null    float64
 3   Low              225 non-null    float64
 4   Close            212 non-null    float64
 5   Volume           226 non-null    object
 6   Predicted_Close  222 non-null    float64
 7   Currency_Pair    229 non-null    object
 8   Signal           227 non-null    object
 9   Confidence       218 non-null    float64
dtypes: float64(6), object(4)
memory usage: 18.0+ KB

In [8]:
df.isnull().sum()

Date                3
Open                5
High                9
Low                 4
Close              17
Volume              3
Predicted_Close     7
Currency_Pair       0
Signal              2
Confidence         11
dtype: int64

In [9]:
df['Date'].fillna(df['Date'].mode(), inplace=True)

df['Open'].fillna(df['Open'].mean(), inplace=True)

df['High'].fillna(df['High'].mean(), inplace=True)

df['Low'].fillna(df['Low'].mean(), inplace=True)

df['Close'].fillna(df['Close'].mean(), inplace=True)

df['Predicted_Close'].fillna(df['Predicted_Close'].mean(), inplace=True)

df['Signal'].fillna(df['Signal'].mode(), inplace=True)

df['Confidence'].fillna(df['Confidence'].mean(), inplace=True)

C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna(df['Date'].mode(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Open'].fillna(df['Open'].mean(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['High'].fillna(df['High'].mean(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Low'].fillna(df['Low'].mean(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Close'].fillna(df['Close'].mean(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Predicted_Close'].fillna(df['Predicted_Close'].mean(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Signal'].fillna(df['Signal'].mode(), inplace=True)
C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\4137098183.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Confidence'].fillna(df['Confidence'].mean(), inplace=True)

In [11]:
df['Volume'] = pd.to_numeric(df['Volume'], errors='coerce')

df['Volume'].fillna(df['Volume'].mean(), inplace=True)

C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\2415582295.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Volume'].fillna(df['Volume'].mean(), inplace=True)

In [16]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

df['Date'].fillna(df['Date'].median(), inplace=True)

C:\Users\LIONESS\AppData\Local\Temp\ipykernel_12908\3469714496.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Date'].fillna(df['Date'].median(), inplace=True)

In [23]:
df['Signal'].fillna(df['Signal'].mode()[0], inplace=True)

In [24]:
df.isnull().sum()

Date               0
Open               0
High               0
Low                0
Close              0
Volume             0
Predicted_Close    0
Currency_Pair      0
Signal             0
Confidence         0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(10)